export const milestonesData = [
  {
    year: "2022",
    date: "feb2022",
    title: "establishedTitle",
    detail: "establishedDetails",
    row: false,
  },
  {
    year: "2022",
    date: "q12022",
    title: "phase1",
    detail: "aboutphase1",
    row: true,
  },
  {
    year: "2022",
    date: "q12022",
    title: "website",
    detail: "aboutwebsite",
    row: true,
  },
  {
    year: "2022",
    date: "q12022",
    title: "explorerandtelemetry",
    detail: "aboutexplorerandtelemetry",
    row: false,
  },
  {
    year: "2022",
    date: "q12022",
    title: "community",
    detail: "aboutcommunity",
    row: false,
  },
  {
    year: "2022",
    date: "q12022",
    title: "tools",
    detail: "abouttools",
    row: false,
  },
  {
    date: "q2q32022",
    title: "phase2",
    detail: "aboutphase2",
    row: false,
  },
  {
    year: "2022",
    date: "q2q32022",
    title: "servicemigration",
    detail: "aboutservicemigration",
    row: false,
  },
  {
    year: "2022",
    date: "q2q32022",
    title: "partnerships",
    detail: "aboutpartnerships",
    row: false,
  },
  {
    year: "2022",
    date: "q2q32022",
    title: "securestaking",
    detail: "aboutsecurestaking",
    row: false,
  },
  {
    year: "2022",
    date: "q2q32022",
    title: "charitydao",
    detail: "aboutcharitydao",
    row: false,
  },
  {
    year: "2023",
    date: "all2023",
    title: "phase3",
    detail: "aboutphase3",
    row: false,
  },
];
